import { createContext } from 'svelte';

interface LayerCakeContext {
	activeGetters: {
		x?: Function | null | undefined;
		y?: Function | null | undefined;
		z?: Function | null | undefined;
		r?: Function | null | undefined;
	};
	width: number;
	height: number;
	percentRange: boolean;
	aspectRatio: number;
	containerWidth: number;
	containerHeight: number;
	x: Function | null | undefined;
	y: Function | null | undefined;
	z: Function | null | undefined;
	r: Function | null | undefined;
	custom: {};
	data: {} | Array<{}>;
	xNice: number | boolean;
	yNice: number | boolean;
	zNice: number | boolean;
	rNice: number | boolean;
	xDomainSort: boolean;
	yDomainSort: boolean;
	zDomainSort: boolean;
	rDomainSort: boolean;
	xReverse: boolean;
	yReverse: boolean | undefined;
	zReverse: boolean;
	rReverse: boolean;
	xPadding: [leftPixels: number, rightPixels: number] | undefined;
	yPadding: [leftPixels: number, rightPixels: number] | undefined;
	zPadding: [leftPixels: number, rightPixels: number] | undefined;
	rPadding: [leftPixels: number, rightPixels: number] | undefined;
	padding: { top: number; right: number; bottom: number; left: number };
	flatData: {} | Array<{} | any>;
	extents: {};
	xDomain: any;
	yDomain: any;
	zDomain: any;
	rDomain: any;
	xRange: any;
	yRange: any;
	zRange: any;
	rRange: any;
	config: {};
	xScale: any;
	yScale: any;
	zScale: any;
	rScale: any;
	xGet: any;
	yGet: any;
	zGet: any;
	rGet: any;
}

export const [getLayerCakeContext, setLayerCakeContext] = createContext<LayerCakeContext>();
