export default [
	{ state_name: 'Alaska', party: 'R', name: 'Daniel Sullivan', gender: 'male', date_of_birth: '1964-11-13' },
	{ state_name: 'Alaska', party: 'R', name: 'Lisa Murkowski', gender: 'female', date_of_birth: '1957-05-22' },
	{ state_name: 'Alabama', party: 'D', name: 'Gordon Jones', gender: 'male', date_of_birth: '1954-05-04' },
	{ state_name: 'Alabama', party: 'R', name: 'Richard Shelby', gender: 'male', date_of_birth: '1934-05-06' },
	{ state_name: 'Arkansas', party: 'R', name: 'John Boozman', gender: 'male', date_of_birth: '1950-12-10' },
	{ state_name: 'Arkansas', party: 'R', name: 'Tom Cotton', gender: 'male', date_of_birth: '1977-05-13' },
	{ state_name: 'Arizona', party: 'D', name: 'Kyrsten Sinema', gender: 'female', date_of_birth: '1976-07-12' },
	{ state_name: 'Arizona', party: 'R', name: 'Martha McSally', gender: 'female', date_of_birth: '1966-03-22' },
	{ state_name: 'California', party: 'D', name: 'Dianne Feinstein', gender: 'female', date_of_birth: '1933-06-22' },
	{ state_name: 'California', party: 'D', name: 'Kamala Harris', gender: 'female', date_of_birth: '1964-10-20' },
	{ state_name: 'Colorado', party: 'R', name: 'Cory Gardner', gender: 'male', date_of_birth: '1974-08-22' },
	{ state_name: 'Colorado', party: 'D', name: 'Michael Bennet', gender: 'male', date_of_birth: '1964-11-28' },
	{ state_name: 'Connecticut', party: 'D', name: 'Christopher Murphy', gender: 'male', date_of_birth: '1973-08-03' },
	{ state_name: 'Connecticut', party: 'D', name: 'Richard Blumenthal', gender: 'male', date_of_birth: '1946-02-13' },
	{ state_name: 'Delaware', party: 'D', name: 'Christopher Coons', gender: 'male', date_of_birth: '1963-09-09' },
	{ state_name: 'Delaware', party: 'D', name: 'Thomas Carper', gender: 'male', date_of_birth: '1947-01-23' },
	{ state_name: 'Florida', party: 'R', name: 'Rick Scott', gender: 'male', date_of_birth: '1952-12-01' },
	{ state_name: 'Florida', party: 'R', name: 'Marco Rubio', gender: 'male', date_of_birth: '1971-05-28' },
	{ state_name: 'Georgia', party: 'R', name: 'David Perdue', gender: 'male', date_of_birth: '1949-12-10' },
	{ state_name: 'Georgia', party: 'R', name: 'Johnny Isakson', gender: 'male', date_of_birth: '1944-12-28' },
	{ state_name: 'Hawaii', party: 'D', name: 'Brian Schatz', gender: 'male', date_of_birth: '1972-10-20' },
	{ state_name: 'Hawaii', party: 'D', name: 'Mazie Hirono', gender: 'female', date_of_birth: '1947-11-03' },
	{ state_name: 'Iowa', party: 'R', name: 'Joni Ernst', gender: 'female', date_of_birth: '1970-07-01' },
	{ state_name: 'Illinois', party: 'D', name: 'Richard Durbin', gender: 'male', date_of_birth: '1944-11-21' },
	{ state_name: 'Idaho', party: 'R', name: 'James Risch', gender: 'male', date_of_birth: '1943-05-03' },
	{ state_name: 'Illinois', party: 'D', name: 'Tammy Duckworth', gender: 'female', date_of_birth: '1968-03-12' },
	{ state_name: 'Indiana', party: 'R', name: 'Todd Young', gender: 'male', date_of_birth: '1972-08-24' },
	{ state_name: 'Kansas', party: 'R', name: 'Jerry Moran', gender: 'male', date_of_birth: '1954-05-29' },
	{ state_name: 'Kansas', party: 'R', name: 'Pat Roberts', gender: 'male', date_of_birth: '1936-04-20' },
	{ state_name: 'Kentucky', party: 'R', name: 'Mitch McConnell', gender: 'male', date_of_birth: '1942-02-20' },
	{ state_name: 'Kentucky', party: 'R', name: 'Rand Paul', gender: 'male', date_of_birth: '1963-01-07' },
	{ state_name: 'Louisiana', party: 'R', name: 'Bill Cassidy', gender: 'male', date_of_birth: '1957-09-28' },
	{ state_name: 'Louisiana', party: 'R', name: 'John Kennedy', gender: 'male', date_of_birth: '1951-11-21' },
	{ state_name: 'Massachusetts', party: 'D', name: 'Edward Markey', gender: 'male', date_of_birth: '1946-11-11' },
	{ state_name: 'Massachusetts', party: 'D', name: 'Elizabeth Warren', gender: 'female', date_of_birth: '1949-06-22' },
	{ state_name: 'Maryland', party: 'D', name: 'Benjamin Cardin', gender: 'male', date_of_birth: '1943-10-05' },
	{ state_name: 'Maryland', party: 'D', name: 'Chris Van Hollen', gender: 'male', date_of_birth: '1959-01-10' },
	{ state_name: 'Maine', party: 'I', name: 'Angus King', gender: 'male', date_of_birth: '1944-03-31' },
	{ state_name: 'Maine', party: 'R', name: 'Susan Collins', gender: 'female', date_of_birth: '1952-12-07' },
	{ state_name: 'Michigan', party: 'D', name: 'Debbie Stabenow', gender: 'female', date_of_birth: '1950-04-29' },
	{ state_name: 'Michigan', party: 'D', name: 'Gary Peters', gender: 'male', date_of_birth: '1958-01-01' },
	{ state_name: 'Minnesota', party: 'D', name: 'Tina Smith', gender: 'female', date_of_birth: '1958-03-04' },
	{ state_name: 'Minnesota', party: 'D', name: 'Amy Klobuchar', gender: 'female', date_of_birth: '1960-05-25' },
	{ state_name: 'Missouri', party: 'R', name: 'Josh Hawley', gender: 'male', date_of_birth: '1979-12-31' },
	{ state_name: 'Indiana', party: 'R', name: 'Mike Braun', gender: 'male', date_of_birth: '1954-03-24' },
	{ state_name: 'Mississippi', party: 'R', name: 'Roger Wicker', gender: 'male', date_of_birth: '1951-07-05' },
	{ state_name: 'Mississippi', party: 'R', name: 'Cindy Hyde-Smith', gender: 'female', date_of_birth: '1959-05-10' },
	{ state_name: 'Iowa', party: 'R', name: 'Charles Grassley', gender: 'male', date_of_birth: '1933-09-17' },
	{ state_name: 'Montana', party: 'R', name: 'Steve Daines', gender: 'male', date_of_birth: '1962-08-20' },
	{ state_name: 'Idaho', party: 'R', name: 'Mike Crapo', gender: 'male', date_of_birth: '1951-05-20' },
	{ state_name: 'Missouri', party: 'R', name: 'Roy Blunt', gender: 'male', date_of_birth: '1950-01-10' },
	{ state_name: 'North Dakota', party: 'R', name: 'Kevin Cramer', gender: 'male', date_of_birth: '1961-01-21' },
	{ state_name: 'North Dakota', party: 'R', name: 'John Hoeven', gender: 'male', date_of_birth: '1957-03-13' },
	{ state_name: 'Montana', party: 'D', name: 'Jon Tester', gender: 'male', date_of_birth: '1956-08-21' },
	{ state_name: 'North Carolina', party: 'R', name: 'Richard Burr', gender: 'male', date_of_birth: '1955-11-30' },
	{ state_name: 'North Carolina', party: 'R', name: 'Thom Tillis', gender: 'male', date_of_birth: '1960-08-30' },
	{ state_name: 'Nebraska', party: 'R', name: 'Ben Sasse', gender: 'male', date_of_birth: '1972-02-22' },
	{ state_name: 'Nebraska', party: 'R', name: 'Deb Fischer', gender: 'female', date_of_birth: '1951-03-01' },
	{ state_name: 'New Hampshire', party: 'D', name: 'Jeanne Shaheen', gender: 'female', date_of_birth: '1947-01-28' },
	{ state_name: 'New Hampshire', party: 'D', name: 'Margaret Hassan', gender: 'female', date_of_birth: '1958-02-27' },
	{ state_name: 'New Jersey', party: 'D', name: 'Cory Booker', gender: 'male', date_of_birth: '1969-04-27' },
	{ state_name: 'New Jersey', party: 'D', name: 'Robert Menendez', gender: 'male', date_of_birth: '1954-01-01' },
	{ state_name: 'New Mexico', party: 'D', name: 'Martin Heinrich', gender: 'male', date_of_birth: '1971-10-17' },
	{ state_name: 'New Mexico', party: 'D', name: 'Tom Udall', gender: 'male', date_of_birth: '1948-05-18' },
	{ state_name: 'Nevada', party: 'D', name: 'Catherine Cortez-Masto', gender: 'female', date_of_birth: '1964-03-29' },
	{ state_name: 'Nevada', party: 'D', name: 'Jacky Rosen', gender: 'female', date_of_birth: '1957-08-02' },
	{ state_name: 'New York', party: 'D', name: 'Charles Schumer', gender: 'male', date_of_birth: '1950-11-23' },
	{ state_name: 'New York', party: 'D', name: 'Kirsten Gillibrand', gender: 'female', date_of_birth: '1966-12-09' },
	{ state_name: 'Ohio', party: 'R', name: 'Rob Portman', gender: 'male', date_of_birth: '1955-12-19' },
	{ state_name: 'Ohio', party: 'D', name: 'Sherrod Brown', gender: 'male', date_of_birth: '1952-11-09' },
	{ state_name: 'Oklahoma', party: 'R', name: 'James Inhofe', gender: 'male', date_of_birth: '1934-11-17' },
	{ state_name: 'Oklahoma', party: 'R', name: 'James Lankford', gender: 'male', date_of_birth: '1968-03-04' },
	{ state_name: 'Oregon', party: 'D', name: 'Jeff Merkley', gender: 'male', date_of_birth: '1956-10-24' },
	{ state_name: 'Oregon', party: 'D', name: 'Ron Wyden', gender: 'male', date_of_birth: '1949-05-03' },
	{ state_name: 'Pennsylvania', party: 'R', name: 'Patrick Toomey', gender: 'male', date_of_birth: '1961-11-17' },
	{ state_name: 'Pennsylvania', party: 'D', name: 'Robert Casey', gender: 'male', date_of_birth: '1960-04-13' },
	{ state_name: 'Rhode Island', party: 'D', name: 'Jack Reed', gender: 'male', date_of_birth: '1949-11-12' },
	{ state_name: 'Rhode Island', party: 'D', name: 'Sheldon Whitehouse', gender: 'male', date_of_birth: '1955-10-20' },
	{ state_name: 'South Carolina', party: 'R', name: 'Lindsey Graham', gender: 'male', date_of_birth: '1955-07-09' },
	{ state_name: 'South Carolina', party: 'R', name: 'Tim Scott', gender: 'male', date_of_birth: '1965-09-19' },
	{ state_name: 'South Dakota', party: 'R', name: 'John Thune', gender: 'male', date_of_birth: '1961-01-07' },
	{ state_name: 'South Dakota', party: 'R', name: 'Mike Rounds', gender: 'male', date_of_birth: '1954-10-24' },
	{ state_name: 'Tennessee', party: 'R', name: 'Marsha Blackburn', gender: 'female', date_of_birth: '1952-06-06' },
	{ state_name: 'Tennessee', party: 'R', name: 'Lamar Alexander', gender: 'male', date_of_birth: '1940-07-03' },
	{ state_name: 'Texas', party: 'R', name: 'John Cornyn', gender: 'male', date_of_birth: '1952-02-02' },
	{ state_name: 'Texas', party: 'R', name: 'Ted Cruz', gender: 'male', date_of_birth: '1970-12-22' },
	{ state_name: 'Utah', party: 'R', name: 'Mike Lee', gender: 'male', date_of_birth: '1971-06-04' },
	{ state_name: 'Utah', party: 'R', name: 'Mitt Romney', gender: 'male', date_of_birth: '1947-03-12' },
	{ state_name: 'Virginia', party: 'D', name: 'Mark Warner', gender: 'male', date_of_birth: '1954-12-15' },
	{ state_name: 'Virginia', party: 'D', name: 'Tim Kaine', gender: 'male', date_of_birth: '1958-02-26' },
	{ state_name: 'Vermont', party: 'I', name: 'Bernard Sanders', gender: 'male', date_of_birth: '1941-09-08' },
	{ state_name: 'Vermont', party: 'D', name: 'Patrick Leahy', gender: 'male', date_of_birth: '1940-03-31' },
	{ state_name: 'Washington', party: 'D', name: 'Maria Cantwell', gender: 'female', date_of_birth: '1958-10-13' },
	{ state_name: 'Washington', party: 'D', name: 'Patty Murray', gender: 'female', date_of_birth: '1950-10-11' },
	{ state_name: 'Wisconsin', party: 'R', name: 'Ron Johnson', gender: 'male', date_of_birth: '1955-04-08' },
	{ state_name: 'Wisconsin', party: 'D', name: 'Tammy Baldwin', gender: 'female', date_of_birth: '1962-02-11' },
	{ state_name: 'West Virginia', party: 'D', name: 'Joe Manchin', gender: 'male', date_of_birth: '1947-08-24' },
	{ state_name: 'West Virginia', party: 'R', name: 'Shelley Capito', gender: 'female', date_of_birth: '1953-11-26' },
	{ state_name: 'Wyoming', party: 'R', name: 'John Barrasso', gender: 'male', date_of_birth: '1952-07-21' },
	{ state_name: 'Wyoming', party: 'R', name: 'Michael Enzi', gender: 'male', date_of_birth: '1944-02-01' }
];
